name: flick_video_player
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
repository: https://github.com/GeekyAnts/flick-video-player
homepage: https://github.com/GeekyAnts/flick-video-player

version: 0.5.2

environment:
  sdk: ">=3.0.0 <3.15.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: 2.8.6
  provider: 6.1.2
  wakelock_plus: 1.2.5
  universal_html: 2.2.4
  dio: 5.4.3+1 
  path_provider: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
